### ISSUE TITLE
Allocating for Exposure Key export fails due to limited RAM

### ISSUE THREAD

**Issue by Lurkars** [Lurkars/esp-ena#3]
Currently there is not enough RAM to process ena-cwa.c#ena_cwa_receive_keys web request. A solution is needed to free memory before downloading zip and unzipping. Possible levers
- free temporary beacons
- stop BL(E) stack during this
- stop interface during this

**Comment by pinkit-cwa** [comment]
I already described a mechanism to off-load received EN beacon information to flash (read from ["Further plans are:"](https://github.com/CovidBraceletPrj/CovidBracelet/issues/1#issuecomment-674348600) ). I by now found a suitable base "file system" called "flash circular buffer", and am willing to implement that as a next step, if you agree. That way I think RAM usage for EN beacons would get close to zero, most of the time (just not right during scans).

Please confirm, so we won't be working on this in parallel.

**Comment by Lurkars** [comment]
My research suggest, that I have to abandon the idea of unzipping on device. https://www.reddit.com/r/esp32/comments/ibzyxx/help_unzip_read_file_from_zip/ so freeing up memory doesn't seem as a solution. Besides that for other devices it is a good idea to do so anyways.

But I want to create a new branch for zephyr development not to break current status. I don't know if possible to move pull request to other branch, will have a look at this in the next days.

**Comment by pinkit-cwa** [comment]
I am currently working on a new implementation of ena-storage, based on flash circular buffer. Properties:
- RAM usage only during scan. Between scans, everything is stored in flash. That implies that I store all receive beacons, even if seen just once.
- RAM usage during scan around 16 kBytes; if needed this might also be reduced to around 8kBytes if needed

I found some cheap wristbands called ID107HR, 15 EUR per piece. Properties: 32kBytes RAM, 256MB Flash. Might be enough for 2 hours with 800 contacts, but also for 14 days  with low number of contacts (up to 4 contacts 24/7 for 14 days, if the code can be fit into about 60kBytes, and we do not store full received beacons). I think that is the low end for a wristband with display.

Cheaper solutions would be pebble-like: no display, just battery and BT chipset, for around 5EUR. Those will probably be less resource-constrained than ID107HR (more RAM and more flash), but maybe with no second life after corona.

**Comment by pinkit-cwa** [comment]
Unzipping 10kBytes of data takes > 240kBytes of RAM? How big is the unzipped data?

Well, not implausible. But it may also be possible to modify the implementation to trade-in RAM-usage for computational power. Swapping to flash probably is not an option.

Maybe it could be possible to have some proxy that performs the unzipping. Issue here would be trust into this proxy - unless the signature is for the unzipped data.

I am not sure about the used file format / did not download/unzip yet, but probably this is some bloated ASCII file / JSON / XML file. If just the (random => uncompressable) TEKs and some (well-compressable) information about the exposure would be stored, I do not think that this file would even have to be zipped.

**Comment by Lurkars** [comment]
is drepecated now in favour of proxy server for providing keys in binary format with pagination.
